# ------------------------------------------------------------------------------
#          ---        
#        / o o \    Project:  cov-phydyn
#        V\ Y /V    Config file SARS-CoV-2 MTBD phylodynamic analysis pipeline
#    (\   / - \     2 December 2022 modified on 26 January 2023
#     )) /    |     
#     ((/__) ||     Code by Ceci VA 
# ------------------------------------------------------------------------------


run:
  dataset: "example_data"
  beast_analysis: "example_analysis_deathrate36"

lapis:
  database: "open"
  seq_id: "genbankAccession"
  access_key: null

# One dataset per deme
data:
  example_data:
    deme1:
      # ids_file:
      nextcladeQcOverallScoreFrom: 0
      nextcladeQcOverallScoreTo: 10
      country: "Switzerland"
      dateFrom: "2020-12-29"
      dateTo: "2021-02-27"
      n: 50

    deme2:
      nextcladeQcOverallScoreFrom: 0
      nextcladeQcOverallScoreTo: 10
      country: "France"
      dateFrom: "2020-12-29"
      dateTo: "2021-02-27"
      n: 50

subsample: # random, cases or uniform
  method: ["cases", "uniform"]
  replicates: 3

files:
  cases: "resources/example_cases.csv" # for cases subsampling method
  include: null
  exclude: null

ml_tree:
  tree_args: " -m GTR -nstop 50 -ninit 20 -bb 1000 " #--date TAXNAME -o 'EPI_ISL_406798|China|2019-12-26' for time tree

beast:
  jar: "resources/2301_BDMM-Prime.jar"
  length: 10000000
  time: 7200
  mem_mb: 4096
  threads: 10
  burnin: 10
  
  example_analysis_deathrate36:
    xml: "resources/beast_xml/example_analysis.xml"
    chains: 5
    action: "resume"
    model_params:
      death_rate: 36.5
  
  example_analysis_deathrate73:
    xml: "resources/beast_xml/example_analysis.xml"
    chains: 5
    action: "resume"
    model_params:
      death_rate: 73
  

